sudo: required
services:
  - docker

before_install:
  - docker build -t pshastri/react-test -f ./client/Dockerfile.dev ./client
#primary test running section. if any of these fails trvis-ci fails
script:
  - docker run pshastri/react-test npm test -- --coverage

after_success: 
  - docker build -t pshastri/multi-client ./client
  - docker build -t pshastri/multi-worker ./worker
  - docker build -t pshastri/multi-nginx ./nginx
  - docker build -t pshastri/multi-server ./server
  #log in to docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  #Take those images and push them to docker hub
  - docker push pshastri/multi-client
  - docker push pshastri/multi-nginx
  - docker push pshastri/multi-server
  - docker push pshastri/multi-worker